spring.main.banner-mode=console
spring.output.ansi.enabled=always

spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.enabled=true
spring.liquibase.drop-first=false
spring.liquibase.default-schema=${SCHEMA:moto}

spring.jpa.properties.hibernate.default_schema=${SCHEMA:moto}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.format_sql=false
spring.jpa.properties.show_sql=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=false

debug=false
logging.level.root=info
