spring.application.name=moto-service
spring.profiles.active=${PROFILE_ACTIVE:dev}
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/changelog.yaml
spring.jpa.open-in-view=false
server.port=${PORT:7059}
springdoc.writer-with-order-by-keys=true

introspection.uri=${INTROSPECTION_URI:http://localhost:7051/api/v1/auth/introspect}
introspection.client-id=${INTROSPECTION_CLIENT_ID:moto-service}
introspection.client-secret=${INTROSPECTION_CLIENT_SECRET:MyS3cur3Cli3ntS3cr3t!M0t0!}
